### ISSUE TITLE
[NOT A ISSUE] Just to say thanks🙇‍♂️

### ISSUE THREAD

**Issue by vacous** [YinlinHu/pypdfium#6]
Hi, thanks for the effort of creating this non-GPL licensed package. I have spent weeks trying to workaround GPL licensed pdf package and this is the only one that really works (and even faster than those poppler backend ones).

**Comment by adam-huganir** [comment]
Agreed, much faster than `pdftoppm` makes a huge difference in our pipeline

**Comment by mara004** [comment]
Yeah, PDFium is notably faster than many other PDF rendering libraries, and its liberal Apache2 or BSD license makes it very interesting.
However, these Python bindings have a considerable drawback concerning interoperability: Only 64-bit Linux, macOS and Windows are supported, and all binaries are packed into one wheel that is misleadingly marked as  "universal". This packaging style also makes the wheel larger than necessary (two unneeded binaries are deployed to the end-user).

Since I personally need a liberal-licensed, maintained, cross-platform Python PDF rendering library, I'm currently planning a full rewrite of PyPDFium to build separate wheels for each platform supported by upstream pdfium-binaries. However, I'm not sure whether I'm up to this task...

Furthermore, if you are using pypdfium in "real" projects that are intended to be used professionally, you should note that licensing information is currently incomplete, as pointed out by `@bgermann`.

**Comment by mara004** [comment]
> I'm currently planning a full rewrite of PyPDFium to build separate wheels for each platform supported by upstream pdfium-binaries.

Not sure whether this thread is the right place for this, but: I've finally sat down and tried building separate wheels. I've rewritten everything and built experimental packages. However, I would need testers for all platforms before I can release anything:

* macOS arm 64-bit (pypdfium2-0.2.0b0-py3-none-macosx_none_arm64.whl)
* macOS intel 64-bit (pypdfium2-0.2.0b0-py3-none-macosx_none_intel.whl)
* Linux arm 64-bit (pypdfium2-0.2.0b0-py3-none-manylinux_2_17_aarch64.whl)
* Linux amd 64-bit (pypdfium2-0.2.0b0-py3-none-manylinux_2_17_x86_64.whl) (→ already tested by myself)
* Windows 64-bit (pypdfium2-0.2.0b0-py3-none-win_amd64.whl)
* Windows 32-bit (pypdfium2-0.2.0b0-py3-none-win32.whl)

I've renamed the module to pypdfium2 due to the drastic setup changes; however, everything else should work exactly the same way as before. For testing, please download the attached archive, extract it and install the relevant wheel using pip:

```bash
cd $your_wheel_directory
python3 -m pip install $your_wheel
```

Then run the example with any PDF of your choice:

```bash
python3 example.py $your_pdf
```

If all went well, a file named 'out.png' showing the first page of your document should have been created.
Please report success or failiure here.

~~https://github.com/YinlinHu/pypdfium/files/7391130/pypdfium2-0.2.0b0-py3.zip~~
Update: Please use the new attachment from https://github.com/YinlinHu/pypdfium/issues/6#issuecomment-949728110 instead

**Comment by adam-huganir** [comment]
@mara004 I can test win64, linux arm and maybe win32 in the next few days, hopefully sooner rather than later

**Comment by mara004** [comment]
Nice, thanks! Take your time.

**Comment by mara004** [comment]
A small update:
* I've been able to test the Windows 64-bit wheel, and library load currently fails because the binary is only named `pdfium`, but on Windows apparently it must be `pdfium.dll`.
* Concerning Linux arm64 I just realised the binary is actually arm32 (e. g. raspberry pi). However, arm64 support got added to pdfium-binaries today.
* Concerning macOS, the wheel should be tagged as `...x86_64` rather than `intel`. However, I'm not sure how the binary needs to be named on mac.

**Comment by mara004** [comment]
New wheels archive that should hopefully fix the problems mentioned in my previous comment:
[pypdfium2-0.3.0b0.zip](https://github.com/YinlinHu/pypdfium/files/7399489/pypdfium2-0.3.0b0.zip)

There is now an armv7l wheel (pypdfium2-0.3.0b0-py3-none-manylinux_2_17_armv7l.whl) that I already tested on a Raspberry Pi 2b with Debian 9 and Python 3.9 (works 🎉).

**Comment by adam-huganir** [comment]
@mara004 awesome.

As to the mac one, the mac specific one is `.dylib` i think, so maybe that? Also `.so` may work there as well as linux. Probably one of those if it doesn't like it as is

**Comment by mara004** [comment]
> As to the mac one, the mac specific one is .dylib i think, so maybe that? 

Yeah, I've just renamed it to .dylib - unfortunately I currently don't have access to a mac device to confirm it works.

**Comment by mara004** [comment]
While attempting an upload on [TestPyPI](https://test.pypi.org/legacy/) I realised the platform tag of the mac wheels is still wrong. According to [realpython/python-wheels](https://realpython.com/python-wheels/), the second part of the platform tag may not be `none`, but instead needs to be the macOS developer tools SDK version. To what should I set this? Are the wheels at all compatible with macOS if they are built on Linux?
For [Pillow](https://pypi.org/project/Pillow/#files), the macOS SDK version currently seems to be `10_10` for  x86_64 and `11_0` for arm64...

**Comment by mara004** [comment]
@adam-huganir I've pushed my current pypdfium2 code base into a (still private) github repository and invited you and @mkroutikov as contributors. If you could send me your PyPI account name I'd like to give you upload access once the project is published on PyPI.

**Comment by mara004** [comment]
@vacous pypdfium2 is now published and brings several improvements. It would be nice if you could give it a try:
```bash
python3 -m pip install pypdfium2
```
https://github.com/pypdfium2-team/pypdfium2
